server:
  port: 8007
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.0.111
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true