server:
  port: 80
spring:
  application:
    name: consumer-hystrix-feign-order-service
eureka:
  instance:
    instance-id: consumer-hystrix-feign-order80
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true

#作为消费方,OpenFeign使用hystrix熔断需要开启
feign:
  hystrix:
    enabled: true