server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider-service
  cloud:
    stream:
      binders: #配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称,用于binding整合,[自定义]
          type: rabbit #消息组件类型
          enviroment:
            rabbitmq:
              host: localhost
              port: 5672
              username: guest
              password: guest
      bindings: #服务的整合处理
        output: #通道名称,[自定义]
          destination: ownerExchange #要使用的exchange名称
          content-type: application/json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    instance-id: send-8801.com
