server:
  port: 9527

spring:
  application:
    name: gateway-service
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由,用服务名转发路由
          lower-case-service-id: false
      routes:
      - id: service_payment__v1
        uri: lb://provider-payment-service
        predicates:
          - Path=/api/**
          #- After=2020-05-18T17:38:44.383+08:00[GMT+08:00]
          - Between=2020-06-03T10:44:42.383+08:00[GMT+08:00],2020-06-03T10:46:12.383+08:00[GMT+08:00]
          #...接近19种路由断言工厂
#      - id: baidu
#        uri: https://www.baidu.com
#        predicates:
#          - Path=/s
#          - Query=wd
#          - Between=2020-06-03T11:55:42.383+08:00[GMT+08:00],2020-06-03T11:57:12.383+08:00[GMT+08:00]
        filters:
          - StripPrefix=1
provider-payment-service:
  ribbon:
    listOfServer: 192.168.0.104:8001, 192.168.0.104:8002
    #负载算法
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #health检查若宕机，及时剔除掉不可用
    NFLoadBalancerPingClassName: com.liao.springcloud.loadbanlance.HealthExamination
    NFLoadBalancerPingInterval: 2

eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway-service
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
