spring:
  application:
    name: eureka-provider-payment
  profiles:
    active: dev

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liao.springcloud.entity

eureka:
  instance:
    #eureka客户端向服务端发送心跳的时间间隔,单位(秒),默认30s
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待时间上限,单位(秒),默认90s.超时将踢出服务
    lease-expiration-duration-in-seconds: 2
  client:
    healthcheck:
      #开启健康检查（依赖spring-boot-starter-actuator）
      enabled: true