server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  profiles:
    active: dev

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liao.springcloud.entity