server:
  port: 3344

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://192.168.0.41/liaojunbo/cloud2020.git
          username: liaojunbo
          password: 123456789
          #本地仓库
          basedir: F:\learn_spring\cloud2020\cloud 配置中心\cloud2020
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    #暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true